spring.application.name=API-E2T2

# MySQL konexioa
#produkziorako
server.port=8080
server.address=0.0.0.0
spring.datasource.url=jdbc:mysql://erronka-rds.cnwck4qwssja.us-east-1.rds.amazonaws.com:3306/ileapaindegidb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Europe/Madrid
spring.datasource.username=root
spring.datasource.password=ikasle123

# Driver-a automatikoki detektatzen da Spring Boot 3.x-rekin
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver  

# JPA / Hibernate konfigurazioa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Hibernate dialect-a automatikoki detektatzen da
# spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#Spring Security-k memorian erabiltzaile eta pasahitz hauek izango ditu, garapenean zehar autentikatuta egoteko (Postman)
#spring.security.user.name=admin
#spring.security.user.password=1234
